### PR TITLE
Edit to README.md

### PR DESCRIPTION
**Pull request by maytees**
Added Table Of Contents, and a skull creator tutorial. Working on a command manager tutorial and a config manager tutorial. Learnt a lot about Markdown Files. :+1:

### CODE REVIEW

**Comment by maytees** [comment]
Made a mess out of the commits, sorry :face_with_head_bandage:

**Comment by maytees** [comment]
At the end of the reverts: The TOC, Skull Creator, And fix for tab complete bug, are added/fixed

**Comment by maytees** [comment]
Added proper fix to tab complete, thanks @muunitnocQ  for the help.

**Comment by muunitnocQ** [comment]
Closes #7

**Review by KodySimpson — APPROVED** [review]
Looks good, thanks for the documentation homie

**Pull request merged**
