### PR TITLE
Add Gradle info to the Installation section and clean up code a bit

### PR DESCRIPTION
**Pull request by CyberDie22**
Also fix a couple of headers in the Usage section

### CODE REVIEW

**Review by KodySimpson — APPROVED** [review]

**Comment by CyberDie22** [comment]
Are you waiting until you release the plugin before you merge this PR?

**Review by Illuminatiiiiii — APPROVED** [review]
changes look good

**Comment by KodySimpson** [comment]
> Are you waiting until you release the plugin before you merge this PR?

Nah just needed time to look at it

**Comment by CyberDie22** [comment]
Ah ok :)

**Pull request merged**
